plugin:
  name: custom-data-type-gnd
  version: 1.0
  server:
    api-version:
      require: 1
  webfrontend:
    url: build/webfrontend/custom-data-type-gnd.js
    l10n: build/webfrontend/l10n/
custom_types:
  gnd:
    elasticsearch:
      mapping:
        type: l10ntext
      value:
        origin: json
        key: text
    config:
      schema:
        - name: add_differentiatedpersons
          parameters:
            value:
              type: bool
        - name: add_coorporates
          parameters:
            value:
              type: bool
        - name: add_geographicplaces
          parameters:
            value:
              type: bool
        - name: add_subjects
          parameters:
            value:
              type: bool
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool
