plugin:
  name: custom-data-type-gnd
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-gnd
  displayname:
    de-DE: GND-Verknüpfung
    en-US: GND-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit der Gemeinsamen Normdatei (GND) her.
    en-US: Use for references to entities of the Integrated Authority File (GND)
  server:
    api-version:
      require: 1
  scss:
      body:
        - build/webfrontend/custom-data-type-gnd.scss
  webfrontend:
    url: custom-data-type-gnd.js
    l10n: l10n/
custom_types:
  gnd:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      schema:
        - name: add_differentiatedpersons
          parameters:
            value:
              type: bool
        - name: add_coorporates
          parameters:
            value:
              type: bool
        - name: add_geographicplaces
          parameters:
            value:
              type: bool
        - name: add_subjects
          parameters:
            value:
              type: bool
        - name: exact_types
          parameters:
            value:
              type: select
              options: ["ALLE","SubjectHeadingSensoStricto","HistoricSingleEventOrEra","GroupOfPersons","CharactersOrMorphemes","MeansOfTransportWithIndividual_name","FictiveTerm","NomenclatureInBiologyOrChemistry","ProductNameOrBrandName","SoftwareProduct","Language","EthnographicName","MeansOfTransportWithIndividualName","ReligiousTerritory","NaturalGeographicUnit","TerritorialCorporateBodyOrAdministrativeUnit","FictivePlace","BuildingOrMemorial","Country","AdministrativeUnit","ExtraterrestrialTerritory","MemberState","WayBorderOrLine","NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit","FictiveCorporateBody","OrganOfCorporateBody","ProjectOrProgram","Pseudonym","LiteraryOrLegendaryCharacter","Spirits","RoyalOrMemberOfARoyalHouse","CollectivePseudonym","Gods"]
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool
