plugin:
  name: custom-data-type-gnd
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-gnd
  displayname:
    de-DE: GND-Verknüpfung
    en-US: GND-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit der Gemeinsamen Normdatei (GND) her.
    en-US: Use for references to entities of the Integrated Authority File (GND)
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-gnd.js
    l10n: l10n/
custom_types:
  gnd:
    elasticsearch:
      mapping:
        type: object
        properties:
          conceptName:
            type: text
            index: no
            fields:
              exact:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_folded_analyzer
              fulltext:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: sort_de-DE
              suggest:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_suggest_analyzer
              token:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
          conceptURI:
            type: text
            index: no
            fields:
              exact:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_folded_analyzer
              fulltext:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: sort_de-DE
              suggest:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_suggest_analyzer
              token:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
    config:
      schema:
        - name: add_differentiatedpersons
          parameters:
            value:
              type: bool
        - name: add_coorporates
          parameters:
            value:
              type: bool
        - name: add_geographicplaces
          parameters:
            value:
              type: bool
        - name: add_subjects
          parameters:
            value:
              type: bool
        - name: exact_types
          parameters:
            value:
              type: select
              options: ["ALLE","SubjectHeadingSensoStricto","HistoricSingleEventOrEra","GroupOfPersons","CharactersOrMorphemes","MeansOfTransportWithIndividual_name","FictiveTerm","NomenclatureInBiologyOrChemistry","ProductNameOrBrandName","SoftwareProduct","Language","EthnographicName","MeansOfTransportWithIndividualName","ReligiousTerritory","NaturalGeographicUnit","TerritorialCorporateBodyOrAdministrativeUnit","FictivePlace","BuildingOrMemorial","Country","AdministrativeUnit","ExtraterrestrialTerritory","MemberState","WayBorderOrLine","NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit","FictiveCorporateBody","OrganOfCorporateBody","ProjectOrProgram","Pseudonym","LiteraryOrLegendaryCharacter","Spirits","RoyalOrMemberOfARoyalHouse","CollectivePseudonym","Gods"]
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool
